## 使用yml文件替代properties文件，在spring boot启动时默认加载此文件 ##
## database ##
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wangxin?characterEncoding=UTF-8
    username: root
    password: root
  # redis数据库索引（默认为0） #
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
  # thymeleaf模板 #
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

## mybatis ##
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.wangxin.springboot.model

## server port ##
server:
  port: 8081

## 测试value注解注入 ##
x: echlon
y: smash
content: "x: ${x}, y: ${y}"
product:
  car: 1
  bed: 2